# Generated by Django 5.0 on 2023-12-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cargo',
            field=models.CharField(choices=[('A', 'Anvil'), ('B', 'Beer'), ('C', 'Coconut'), ('D', 'Denisovan remains')], default='A', max_length=1),
        ),
    ]
