# Generated by Django 5.0 on 2023-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cage_finch_toys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='cage_type',
            field=models.CharField(max_length=100),
        ),
    ]
